chore: remove links to instruqt demos
momentohq/public-dev-docs pull request #419
Opened 2023-09-08 19:38 UTC by cprice404

2023-09-08 19:40 UTC, allenheltondev requested changes
Can you please also remove the images from the `/img` directory that are no longer in use?

2023-09-08 19:42 UTC, cprice404 commented
> Can you please also remove the images from the `/img` directory that are no longer in use?

38db856e01fd4cbf473eb8037c317261245f06ff

2023-09-08 19:43 UTC, allenheltondev approved these changes, later dismissed

2023-09-11 17:44 UTC, cprice404 commented
@allenheltondev this ended up with a merge conflict so I had to rebase it.

2023-09-11 17:48 UTC, allenheltondev approved these changes

2023-09-11 17:49 UTC, merged