chore: add new top level sidebar for webhooks overview
momentohq/public-dev-docs pull request #551
Opened 2023-12-07 19:57 UTC by bruuuuuuuce

2023-12-07 20:18 UTC, allenheltondev requested changes

2023-12-07 20:18 UTC, allenheltondev commented on docs/topics/webhooks.md
> +Webhooks are outbound HTTP requests sent from a source to a destination. They are fired automatically when the event that they are listening to is fired. They are a key component of facilitating even
replace the first "fired" with "triggered" and the second with "published"

`They are triggered automatically when the event that they are listening to is published`

2023-12-07 20:18 UTC, allenheltondev commented on docs/topics/webhooks.md
> +Webhooks are outbound HTTP requests sent from a source to a destination. They are fired automatically when the event that they are listening to is fired. They are a key component of facilitating even
everywhere that says "event driven" should be hyphenated `event-driven`

2023-12-07 20:18 UTC, allenheltondev commented on docs/topics/webhooks.md
> +You can create a lambda/step function backed by api gateway or use a cloud run function, and have that be the entrypoint to a webhook. When the webhook fires, you lambda/step function can handle the
All these AWS services are proper nouns, so they should be capitalized
* Lambda function
* Step Function workflow
* API Gateway
* Cloud Run function

2023-12-07 20:18 UTC, allenheltondev commented on docs/topics/webhooks.md
> +- [Mulit-Language Chat Application](https://github.com/momentohq/moderated-chat/) This application is a chat application that lets users communicate in multiple languages. Users can select which lang
Typo in alt text - `Multi-Language`

2023-12-07 20:18 UTC, allenheltondev commented on docs/topics/webhooks.md
> +- [Mulit-Language Chat Application](https://github.com/momentohq/moderated-chat/) This application is a chat application that lets users communicate in multiple languages. Users can select which lang
I'd reword for conciseness:
`This chat application lets users automatically communicate in multiple languages.`

2023-12-07 20:18 UTC, allenheltondev commented on docs/topics/webhooks.md
> +- [Mulit-Language Chat Application](https://github.com/momentohq/moderated-chat/) This application is a chat application that lets users communicate in multiple languages. Users can select which lang
Update wording to "Whenever a message **is** sent"

2023-12-07 20:18 UTC, allenheltondev commented on docs/topics/webhooks.md
> +- [Mulit-Language Chat Application](https://github.com/momentohq/moderated-chat/) This application is a chat application that lets users communicate in multiple languages. Users can select which lang
Reword to "The webhook is an API Gateway endpoint backed by a Lambda function which receives all published messages, translates them, then publishes them to all the supported language topics."

2023-12-08 20:59 UTC, cprice404 approved these changes
I'm good when @allenheltondev is!

![yeah](https://media.giphy.com/media/vGa9AafIuJ8OLvHW3X/giphy-downsized.gif)

2023-12-08 21:16 UTC, allenheltondev approved these changes

2023-12-08 21:18 UTC, merged