feat: add webhook patterns
momentohq/public-dev-docs pull request #667
Opened 2024-01-18 08:33 UTC by bruuuuuuuce

2024-01-18 15:14 UTC, allenheltondev requested changes
It feels like most of the steps you have in the async processing page should be in the creating-a-webhook page. We don't have that yet and I think it's a crucial piece that's missing. 

Overall all think we should approach this in a slightly different way. Make the pattern more about ingesting raw data on topic A, processing it, then returning transformed data on topic B.

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/patterns/_category_.json
> +  "label": "Patterns",
I'd like to get @FractalJackal's opinion on whether we should be calling these `Patterns` or `How To`

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +title: Asynchronous Processing
This field shows up on social cards when you paste a direct link to it online or in Slack. Let's retitle it to "Best Practices for Async Process with Momento Topics"

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +description: Learn the how to use Topics and Webhooks to process data asynchronously
This field shows up as the description on social cards, we should be a little more verbose.

"Learn best practices around using Momento Topics and webhooks to process data asynchronously in your event-driven architectures"

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +# Asynchronous Processing with Momento
We're trying to make H1s a little more descriptive, let's go with "Use Momento Topics to process data asynchronously"

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +1. A public facing endpoint to receive webhook events. This endpoint must accept POST requests, and be able to be receive inbound calls from Momento. The structure of the POST body will be of the for
You don't need the comma in the second sentence. Also, please add a colon after the last sentence.

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +1. A public facing endpoint to receive webhook events. This endpoint must accept POST requests, and be able to be receive inbound calls from Momento. The structure of the POST body will be of the for
Let's also add a link to the overview page anchor link where it defines all the properties in this payload.

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +1. [Create Momento Cache](https://console.gomomento.com/caches/create)
"Create a cache in the Momento console."

The way it's worded now sounds like you're talking about the product name

2024-01-18 15:14 UTC, allenheltondev commented on docs/topics/develop/guides/creating-a-webhook.md
> +---
Let's put this in the Webhooks folder and make the sidebar label "Getting started".

2024-01-18 20:29 UTC, cprice404 commented on docs/topics/webhooks/creating-a-webhook.md
> +You should now be able to see the events being received by your webhook endpoint. What this endpoint does with the events is up to you! It is worth noting that this Webhook can listen to multiple top
nice

2024-01-18 20:41 UTC, cprice404 reviewed
looking really good to me! i left a few comments/thoughts that might be worth hitting before we get the next round of feedback from @allenheltondev .

2024-01-18 20:41 UTC, cprice404 commented on static/img/topics/patterns/asynchronous-processing.png
why have 3 topics here? I like this diagram a whole lot, big improvment/simplication from the previous one, but it still seems like there are really only 2 relevant topics here. if you want to show that there can be multiple subscribers and that one of them may be in the original client, that makes sense, but i'd still just call them both "topic 2". and I'd change the arrow on the text to say "Publish Processed Data" in both output paths.

2024-01-18 20:41 UTC, cprice404 commented on docs/topics/develop/patterns/asynchronous-processing.md
> +The key to asynchnously processing these events it to use _multiple_ topics. An inbound topic, which the Webhook listens to, and a single, or multiple, outbound topics which publish the processed dat
I think you can probably remove this last sentence; I think your arch diagram covers this point sufficiently.

2024-01-18 20:41 UTC, cprice404 commented on docs/topics/develop/patterns/asynchronous-processing.md
> +![Architecture](@site/static/img/topics/patterns/asynchronous-processing.png)
it might be worth explicitly mentioning here that in your diagram, "topic 1" is the "inbound" topic, and "topic 2" is the "outbound" topic.

2024-01-18 20:41 UTC, cprice404 commented on docs/topics/develop/patterns/asynchronous-processing.md
> +3. Add code to the Webhook to process the incoming messages
I might add a sentence to this bullet that says "For example, if your webhook is implemented as an AWS Lambda behind an API Gateway, then here is some very simple lambda example code that processes the incoming message, converts it to upper case, and then publishes it to the outbound topic:"

2024-01-18 20:41 UTC, cprice404 commented on docs/topics/develop/patterns/asynchronous-processing.md
> +4. Add a subscriber to this new `topic 2`
Clarify here that you're adding this code to your client application (just to make sure they don't think it is related to the lambda code above).

2024-01-18 20:41 UTC, cprice404 commented on docs/topics/develop/patterns/asynchronous-processing.md
> +And that is it! This Topics pattern allows for clients to be completely agnostic of the downstream consumer, and allows flexibility down the line for consuming messages from the client. For a more co
I might add one or two more sentences here. One that said something like "in the future, if your traffic increases and your server-side component outgrows an environment like webhooks+APIG+Lambda, you can replace the server-side with containers or EC2 resources." and one that said "this is the simplest possible example of basic string conversion, but you can imagine more sophisticated processing use cases such as:

* storing to a database
* moderating using a service like blah blah blah
* eventbridge
"

2024-01-19 20:08 UTC, allenheltondev requested changes

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +title: Best Practices for Async Process with Momento Topics
We don't typically follow title case for titles, ha

"Best practices for async processing with Momento Topics" is my recommendation

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +description: Learn best practices around using Momento Topics and webhooks to process data asynchronously in your event-driven architectures
Can you please add a period to the end of this sentence

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +With Momento Topics, you can subscribe to messages on a Topic, as well as publish messages to a new Topic. Webhooks allow you to connect these Topics to stateless consumers, which can then process th
We need to be wary of upper case Topic vs lower case topic. 

When referring to the service name, we use upper case Momento Topics.

When referring to a topic to publish/subscribe to, we use lower case topic.

I see it mixed a couple of times throughout the page, can you please take a pass at those?

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +With Momento Topics, you can subscribe to messages on a Topic, as well as publish messages to a new Topic. Webhooks allow you to connect these Topics to stateless consumers, which can then process th
I see in here "trigger a step function". Since that's the name of a service, it should be capitalized "Step Function workflow"

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +The key to asynchnously processing these events it to use _multiple_ topics. An inbound topic, which the Webhook listens to, and a single, or multiple, outbound topics which publish the processed dat
typo on 'asynchronously' at the beginning of the sentence. 

Also it says "these events **it** to use" but should be "these events **is** to use".

Please lowercase webhooks everywhere it's used in the middle of a sentence since it's not a proper noun.

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +1. A public facing endpoint to receive webhook events. This endpoint must accept POST requests and be able to receive inbound calls from Momento. More detail about the structure of this event is [des
Please put the period outside of the link

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/develop/patterns/asynchronous-processing.md
> +3. Add code to the Webhook to process the incoming messages. For example, if your webhook is implemented as an AWS Lambda behind an API Gateway, then here is some very simple lambda code that process
We need to make sure we call them "AWS Lambda functions" instead of just "Lambda"

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/webhooks/creating-a-webhook.md
> +sidebar_position: 6
Make this sidebar_position 2 so it shows up underneath Overview

2024-01-19 20:08 UTC, allenheltondev commented on docs/topics/webhooks/creating-a-webhook.md
> +### Creating the Momento webhook
Let's make this an h1 and rephrase 

`# Create your first webhook in Momento`

2024-01-19 21:08 UTC, allenheltondev approved these changes

2024-01-19 22:47 UTC, merged